### ISSUE TITLE
Deploying to Amazon EC2/S3

### ISSUE THREAD

**Issue by hasanr68** [OrecX/Oreka#2]
Hello all,

Unsure where to ask. Want to deploy this with Opensips on an Amazon EC2 server, however, can't seem to find any instructions specific to the setup. Was thinking of saving the audio files on an S3 bucket and oreka to pull from S3 - does that work?

Thanks.

**Comment by oramsaran** [comment]
Hi,

To deploy with OpenSIPS in an EC2 server you will need to contact OrecX for the commercial version called Oreka TR.  That version has OpenSIPS integration and Amazon S3 storage integrated.  sales@orecx.com is the email address.
